version: "3.7"
services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true # if not build app.
    ports:
      - 8001:8001
    environment:
      RUST_BACKTRACE: full
    volumes:
      - ./:/app
